# coding: utf-8

"""
KMSCertificateExpirationDetails.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class KMSCertificateExpirationDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        KMSCertificateExpirationDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'certificate_file_type': 'str',  # (required parameter)
            'expiration_time_of_day': 'str',  # (required parameter)
            'expiration_time': 'int'
        }

        self.attribute_map = {
            'certificate_file_type': 'certificateFileType',  # (required parameter)
            'expiration_time_of_day': 'expirationTimeOfDay',  # (required parameter)
            'expiration_time': 'expirationTime'
        }

        self._certificate_file_type = None
        self._expiration_time_of_day = None
        self._expiration_time = None

    @property
    def certificate_file_type(self):
        """
        Gets the certificate_file_type of this KMSCertificateExpirationDetails.
        Type of KMS certificate for which expiration is being reported.

        :return: The certificate_file_type of this KMSCertificateExpirationDetails.
        :rtype: str
        :required/optional: required
        """
        return self._certificate_file_type

    @certificate_file_type.setter
    def certificate_file_type(self, certificate_file_type):
        """
        Sets the certificate_file_type of this KMSCertificateExpirationDetails.
        Type of KMS certificate for which expiration is being reported.

        :param certificate_file_type: The certificate_file_type of this KMSCertificateExpirationDetails.
        :type: str
        """
        allowed_values = ["certificateFileTypeUnknown", "clientCertificate", "serverCertificate", "__UNDEFINED"]
        if certificate_file_type not in allowed_values:
            raise ValueError(
                "Invalid value for `certificate_file_type`, must be one of {0}"
                .format(allowed_values)
            )
        self._certificate_file_type = certificate_file_type

    @property
    def expiration_time_of_day(self):
        """
        Gets the expiration_time_of_day of this KMSCertificateExpirationDetails.
        Expiration time of day (as a string) for a KMS certificate

        :return: The expiration_time_of_day of this KMSCertificateExpirationDetails.
        :rtype: str
        :required/optional: required
        """
        return self._expiration_time_of_day

    @expiration_time_of_day.setter
    def expiration_time_of_day(self, expiration_time_of_day):
        """
        Sets the expiration_time_of_day of this KMSCertificateExpirationDetails.
        Expiration time of day (as a string) for a KMS certificate

        :param expiration_time_of_day: The expiration_time_of_day of this KMSCertificateExpirationDetails.
        :type: str
        """
        self._expiration_time_of_day = expiration_time_of_day

    @property
    def expiration_time(self):
        """
        Gets the expiration_time of this KMSCertificateExpirationDetails.
        Expiration time of a KMS certificate in seconds since January 1, 1970.

        :return: The expiration_time of this KMSCertificateExpirationDetails.
        :rtype: int
        :required/optional: required
        """
        return self._expiration_time

    @expiration_time.setter
    def expiration_time(self, expiration_time):
        """
        Sets the expiration_time of this KMSCertificateExpirationDetails.
        Expiration time of a KMS certificate in seconds since January 1, 1970.

        :param expiration_time: The expiration_time of this KMSCertificateExpirationDetails.
        :type: int
        """
        self._expiration_time = expiration_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

