# coding: utf-8

"""
NVMeoFBaselinedStatistics.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class NVMeoFBaselinedStatistics(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        NVMeoFBaselinedStatistics - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'time_data': 'StatisticalTimeData',  # (required parameter)
            'nvmeof_interface_statistics_raw': 'list[NVMeoFInterfaceStatistics]',  # (required parameter)
            'nvmeof_interface_statistics_rel': 'list[NVMeoFInterfaceStatistics]'
        }

        self.attribute_map = {
            'time_data': 'timeData',  # (required parameter)
            'nvmeof_interface_statistics_raw': 'nvmeofInterfaceStatisticsRaw',  # (required parameter)
            'nvmeof_interface_statistics_rel': 'nvmeofInterfaceStatisticsRel'
        }

        self._time_data = None
        self._nvmeof_interface_statistics_raw = None
        self._nvmeof_interface_statistics_rel = None

    @property
    def time_data(self):
        """
        Gets the time_data of this NVMeoFBaselinedStatistics.
        The time data associated with this set of statistics.

        :return: The time_data of this NVMeoFBaselinedStatistics.
        :rtype: StatisticalTimeData
        :required/optional: required
        """
        return self._time_data

    @time_data.setter
    def time_data(self, time_data):
        """
        Sets the time_data of this NVMeoFBaselinedStatistics.
        The time data associated with this set of statistics.

        :param time_data: The time_data of this NVMeoFBaselinedStatistics.
        :type: StatisticalTimeData
        """
        self._time_data = time_data

    @property
    def nvmeof_interface_statistics_raw(self):
        """
        Gets the nvmeof_interface_statistics_raw of this NVMeoFBaselinedStatistics.
        An array of structures containing \"raw\" (i.e., baseline = controller start-of-day) NVMe over Fabrics interface statistics, one structure per NVMe over Fabrics interface.

        :return: The nvmeof_interface_statistics_raw of this NVMeoFBaselinedStatistics.
        :rtype: list[NVMeoFInterfaceStatistics]
        :required/optional: required
        """
        return self._nvmeof_interface_statistics_raw

    @nvmeof_interface_statistics_raw.setter
    def nvmeof_interface_statistics_raw(self, nvmeof_interface_statistics_raw):
        """
        Sets the nvmeof_interface_statistics_raw of this NVMeoFBaselinedStatistics.
        An array of structures containing \"raw\" (i.e., baseline = controller start-of-day) NVMe over Fabrics interface statistics, one structure per NVMe over Fabrics interface.

        :param nvmeof_interface_statistics_raw: The nvmeof_interface_statistics_raw of this NVMeoFBaselinedStatistics.
        :type: list[NVMeoFInterfaceStatistics]
        """
        self._nvmeof_interface_statistics_raw = nvmeof_interface_statistics_raw

    @property
    def nvmeof_interface_statistics_rel(self):
        """
        Gets the nvmeof_interface_statistics_rel of this NVMeoFBaselinedStatistics.
        An array of structures containing \"relative\" (i.e., baseline = user pre-set baseline) NVMe over Fabrics interface statistics, one structure per NVMe over Fabrics interface.

        :return: The nvmeof_interface_statistics_rel of this NVMeoFBaselinedStatistics.
        :rtype: list[NVMeoFInterfaceStatistics]
        :required/optional: required
        """
        return self._nvmeof_interface_statistics_rel

    @nvmeof_interface_statistics_rel.setter
    def nvmeof_interface_statistics_rel(self, nvmeof_interface_statistics_rel):
        """
        Sets the nvmeof_interface_statistics_rel of this NVMeoFBaselinedStatistics.
        An array of structures containing \"relative\" (i.e., baseline = user pre-set baseline) NVMe over Fabrics interface statistics, one structure per NVMe over Fabrics interface.

        :param nvmeof_interface_statistics_rel: The nvmeof_interface_statistics_rel of this NVMeoFBaselinedStatistics.
        :type: list[NVMeoFInterfaceStatistics]
        """
        self._nvmeof_interface_statistics_rel = nvmeof_interface_statistics_rel

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

