# coding: utf-8

"""
SSDBlockAllocationScanStatusReturnData.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class SSDBlockAllocationScanStatusReturnData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        SSDBlockAllocationScanStatusReturnData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'scan_status': 'str',  # (required parameter)
            'drive_scan_complete_count': 'int',  # (required parameter)
            'driveblock_allocation_data': 'list[SSDBlockAllocationScanData]'
        }

        self.attribute_map = {
            'scan_status': 'scanStatus',  # (required parameter)
            'drive_scan_complete_count': 'driveScanCompleteCount',  # (required parameter)
            'driveblock_allocation_data': 'driveblockAllocationData'
        }

        self._scan_status = None
        self._drive_scan_complete_count = None
        self._driveblock_allocation_data = None

    @property
    def scan_status(self):
        """
        Gets the scan_status of this SSDBlockAllocationScanStatusReturnData.
        The current status of the block allocation scan of all requested devices.

        :return: The scan_status of this SSDBlockAllocationScanStatusReturnData.
        :rtype: str
        :required/optional: required
        """
        return self._scan_status

    @scan_status.setter
    def scan_status(self, scan_status):
        """
        Sets the scan_status of this SSDBlockAllocationScanStatusReturnData.
        The current status of the block allocation scan of all requested devices.

        :param scan_status: The scan_status of this SSDBlockAllocationScanStatusReturnData.
        :type: str
        """
        allowed_values = ["notStarted", "inProgress", "complete", "__UNDEFINED"]
        if scan_status not in allowed_values:
            raise ValueError(
                "Invalid value for `scan_status`, must be one of {0}"
                .format(allowed_values)
            )
        self._scan_status = scan_status

    @property
    def drive_scan_complete_count(self):
        """
        Gets the drive_scan_complete_count of this SSDBlockAllocationScanStatusReturnData.
        The count of drives that have completed the block allocation scan.

        :return: The drive_scan_complete_count of this SSDBlockAllocationScanStatusReturnData.
        :rtype: int
        :required/optional: required
        """
        return self._drive_scan_complete_count

    @drive_scan_complete_count.setter
    def drive_scan_complete_count(self, drive_scan_complete_count):
        """
        Sets the drive_scan_complete_count of this SSDBlockAllocationScanStatusReturnData.
        The count of drives that have completed the block allocation scan.

        :param drive_scan_complete_count: The drive_scan_complete_count of this SSDBlockAllocationScanStatusReturnData.
        :type: int
        """
        self._drive_scan_complete_count = drive_scan_complete_count

    @property
    def driveblock_allocation_data(self):
        """
        Gets the driveblock_allocation_data of this SSDBlockAllocationScanStatusReturnData.
        List of SSDBlockAllocationScanData, one per valid requested device.

        :return: The driveblock_allocation_data of this SSDBlockAllocationScanStatusReturnData.
        :rtype: list[SSDBlockAllocationScanData]
        :required/optional: required
        """
        return self._driveblock_allocation_data

    @driveblock_allocation_data.setter
    def driveblock_allocation_data(self, driveblock_allocation_data):
        """
        Sets the driveblock_allocation_data of this SSDBlockAllocationScanStatusReturnData.
        List of SSDBlockAllocationScanData, one per valid requested device.

        :param driveblock_allocation_data: The driveblock_allocation_data of this SSDBlockAllocationScanStatusReturnData.
        :type: list[SSDBlockAllocationScanData]
        """
        self._driveblock_allocation_data = driveblock_allocation_data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

