# coding: utf-8

"""
AuditLogGetResponse.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class AuditLogGetResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        AuditLogGetResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'total_log_records': 'int',  # (required parameter)
            'log_records': 'list[AuditLogRecord]',  # (required parameter)
            'first_record_ordinal': 'int',  # (required parameter)
            'last_record_ordinal': 'int'
        }

        self.attribute_map = {
            'total_log_records': 'totalLogRecords',  # (required parameter)
            'log_records': 'logRecords',  # (required parameter)
            'first_record_ordinal': 'firstRecordOrdinal',  # (required parameter)
            'last_record_ordinal': 'lastRecordOrdinal'
        }

        self._total_log_records = None
        self._log_records = None
        self._first_record_ordinal = None
        self._last_record_ordinal = None

    @property
    def total_log_records(self):
        """
        Gets the total_log_records of this AuditLogGetResponse.
        Total audit log records in the database

        :return: The total_log_records of this AuditLogGetResponse.
        :rtype: int
        :required/optional: required
        """
        return self._total_log_records

    @total_log_records.setter
    def total_log_records(self, total_log_records):
        """
        Sets the total_log_records of this AuditLogGetResponse.
        Total audit log records in the database

        :param total_log_records: The total_log_records of this AuditLogGetResponse.
        :type: int
        """
        self._total_log_records = total_log_records

    @property
    def log_records(self):
        """
        Gets the log_records of this AuditLogGetResponse.
        A list of log records requested

        :return: The log_records of this AuditLogGetResponse.
        :rtype: list[AuditLogRecord]
        :required/optional: required
        """
        return self._log_records

    @log_records.setter
    def log_records(self, log_records):
        """
        Sets the log_records of this AuditLogGetResponse.
        A list of log records requested

        :param log_records: The log_records of this AuditLogGetResponse.
        :type: list[AuditLogRecord]
        """
        self._log_records = log_records

    @property
    def first_record_ordinal(self):
        """
        Gets the first_record_ordinal of this AuditLogGetResponse.
        First record ordinal

        :return: The first_record_ordinal of this AuditLogGetResponse.
        :rtype: int
        :required/optional: required
        """
        return self._first_record_ordinal

    @first_record_ordinal.setter
    def first_record_ordinal(self, first_record_ordinal):
        """
        Sets the first_record_ordinal of this AuditLogGetResponse.
        First record ordinal

        :param first_record_ordinal: The first_record_ordinal of this AuditLogGetResponse.
        :type: int
        """
        self._first_record_ordinal = first_record_ordinal

    @property
    def last_record_ordinal(self):
        """
        Gets the last_record_ordinal of this AuditLogGetResponse.
        Last record ordinal

        :return: The last_record_ordinal of this AuditLogGetResponse.
        :rtype: int
        :required/optional: required
        """
        return self._last_record_ordinal

    @last_record_ordinal.setter
    def last_record_ordinal(self, last_record_ordinal):
        """
        Sets the last_record_ordinal of this AuditLogGetResponse.
        Last record ordinal

        :param last_record_ordinal: The last_record_ordinal of this AuditLogGetResponse.
        :type: int
        """
        self._last_record_ordinal = last_record_ordinal

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

