# coding: utf-8

"""
AuditLogConfiguration.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class AuditLogConfiguration(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        AuditLogConfiguration - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'audit_log_max_records': 'int',  # (required parameter)
            'audit_log_level': 'str',  # (required parameter)
            'audit_log_full_policy': 'str',  # (required parameter)
            'audit_log_warning_threshold_pct': 'int'
        }

        self.attribute_map = {
            'audit_log_max_records': 'auditLogMaxRecords',  # (required parameter)
            'audit_log_level': 'auditLogLevel',  # (required parameter)
            'audit_log_full_policy': 'auditLogFullPolicy',  # (required parameter)
            'audit_log_warning_threshold_pct': 'auditLogWarningThresholdPct'
        }

        self._audit_log_max_records = None
        self._audit_log_level = None
        self._audit_log_full_policy = None
        self._audit_log_warning_threshold_pct = None

    @property
    def audit_log_max_records(self):
        """
        Gets the audit_log_max_records of this AuditLogConfiguration.
        Maximum number of records.

        :return: The audit_log_max_records of this AuditLogConfiguration.
        :rtype: int
        :required/optional: required
        """
        return self._audit_log_max_records

    @audit_log_max_records.setter
    def audit_log_max_records(self, audit_log_max_records):
        """
        Sets the audit_log_max_records of this AuditLogConfiguration.
        Maximum number of records.

        :param audit_log_max_records: The audit_log_max_records of this AuditLogConfiguration.
        :type: int
        """
        self._audit_log_max_records = audit_log_max_records

    @property
    def audit_log_level(self):
        """
        Gets the audit_log_level of this AuditLogConfiguration.
        Log level.

        :return: The audit_log_level of this AuditLogConfiguration.
        :rtype: str
        :required/optional: required
        """
        return self._audit_log_level

    @audit_log_level.setter
    def audit_log_level(self, audit_log_level):
        """
        Sets the audit_log_level of this AuditLogConfiguration.
        Log level.

        :param audit_log_level: The audit_log_level of this AuditLogConfiguration.
        :type: str
        """
        allowed_values = ["all", "writeOnly"]
        if audit_log_level not in allowed_values:
            raise ValueError(
                "Invalid value for `audit_log_level`, must be one of {0}"
                .format(allowed_values)
            )
        self._audit_log_level = audit_log_level

    @property
    def audit_log_full_policy(self):
        """
        Gets the audit_log_full_policy of this AuditLogConfiguration.
        Full policy.

        :return: The audit_log_full_policy of this AuditLogConfiguration.
        :rtype: str
        :required/optional: required
        """
        return self._audit_log_full_policy

    @audit_log_full_policy.setter
    def audit_log_full_policy(self, audit_log_full_policy):
        """
        Sets the audit_log_full_policy of this AuditLogConfiguration.
        Full policy.

        :param audit_log_full_policy: The audit_log_full_policy of this AuditLogConfiguration.
        :type: str
        """
        allowed_values = ["overWrite", "preventSystemAccess"]
        if audit_log_full_policy not in allowed_values:
            raise ValueError(
                "Invalid value for `audit_log_full_policy`, must be one of {0}"
                .format(allowed_values)
            )
        self._audit_log_full_policy = audit_log_full_policy

    @property
    def audit_log_warning_threshold_pct(self):
        """
        Gets the audit_log_warning_threshold_pct of this AuditLogConfiguration.
        Warning threshold percentage.

        :return: The audit_log_warning_threshold_pct of this AuditLogConfiguration.
        :rtype: int
        :required/optional: required
        """
        return self._audit_log_warning_threshold_pct

    @audit_log_warning_threshold_pct.setter
    def audit_log_warning_threshold_pct(self, audit_log_warning_threshold_pct):
        """
        Sets the audit_log_warning_threshold_pct of this AuditLogConfiguration.
        Warning threshold percentage.

        :param audit_log_warning_threshold_pct: The audit_log_warning_threshold_pct of this AuditLogConfiguration.
        :type: int
        """
        self._audit_log_warning_threshold_pct = audit_log_warning_threshold_pct

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

