# coding: utf-8

"""
GroupMapping.py

 The Clear BSD License

 Copyright (c) – 2016, NetApp, Inc. All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

 * Neither the name of NetApp, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

 NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from pprint import pformat
from six import iteritems


class GroupMapping(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        GroupMapping - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'group_regex': 'str',  
            'ignorecase': 'bool',  
            'name': 'str'
        }

        self.attribute_map = {
            'group_regex': 'groupRegex',  
            'ignorecase': 'ignorecase',  
            'name': 'name'
        }

        self._group_regex = None
        self._ignorecase = None
        self._name = None

    @property
    def group_regex(self):
        """
        Gets the group_regex of this GroupMapping.
        specifies the DN of the group. The wildcard .* can optionally be used to allow specifying only a partial DN.

        :return: The group_regex of this GroupMapping.
        :rtype: str
        :required/optional: optional
        """
        return self._group_regex

    @group_regex.setter
    def group_regex(self, group_regex):
        """
        Sets the group_regex of this GroupMapping.
        specifies the DN of the group. The wildcard .* can optionally be used to allow specifying only a partial DN.

        :param group_regex: The group_regex of this GroupMapping.
        :type: str
        """
        self._group_regex = group_regex

    @property
    def ignorecase(self):
        """
        Gets the ignorecase of this GroupMapping.
        Whether or not to ignore case for the group mappings

        :return: The ignorecase of this GroupMapping.
        :rtype: bool
        :required/optional: optional
        """
        return self._ignorecase

    @ignorecase.setter
    def ignorecase(self, ignorecase):
        """
        Sets the ignorecase of this GroupMapping.
        Whether or not to ignore case for the group mappings

        :param ignorecase: The ignorecase of this GroupMapping.
        :type: bool
        """
        self._ignorecase = ignorecase

    @property
    def name(self):
        """
        Gets the name of this GroupMapping.
        Specifies the role of the group

        :return: The name of this GroupMapping.
        :rtype: str
        :required/optional: required
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this GroupMapping.
        Specifies the role of the group

        :param name: The name of this GroupMapping.
        :type: str
        """
        allowed_values = ["security_admin", "storage_none", "support_admin", "storage_monitor", "storage_admin"]
        if name not in allowed_values:
            raise ValueError(
                "Invalid value for `name`, must be one of {0}"
                .format(allowed_values)
            )
        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        if self is None:
           return None
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if self is None or other is None:
            return None
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

